backend:
  name: github
  repo: aidanjames/aidanjames.github.io
  branch: main
  base_url: https://aidan-cms-auth.workers.dev
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
site_url: "https://aidanjames.github.io"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Categories",
          name: "categories",
          widget: "string",
          hint: "Use one category (or comma-separated categories)."
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          time_format: false,
          date_format: "YYYY-MM-DD"
        }
      - { label: "Body", name: "body", widget: "markdown" }
